services:
  portfolio_ui:
    container_name: portfolio_ui
    image: portfolio_ui
    build:
      dockerfile: Dockerfile
    environment:
      NGINX_ENVSUBST_OUTPUT_DIR: $NGINX_ENVSUBST_OUTPUT_DIR
      API_SERVICE: $API_SERVICE
      UI_HOST_NAME: $UI_HOST_NAME
