import {
  faArrowRightToBracket,
  faBlog,
  faCalendarDays,
  faCertificate,
  faCheck,
  faCircleExclamation,
  faCircleInfo,
  faCode,
  faContactBook,
  faContactCard,
  faEnvelope,
  faGraduationCap,
  faIdCard,
  faLanguage,
  faListCheck,
  faMapLocationDot,
  faPassport,
  faPenToSquare,
  faPhone,
  faSchoolCircleCheck,
  faTriangleExclamation,
  faUser,
  faUsersLine,
  faXmark,
  faChevronRight,
  faChevronLeft,
} from '@fortawesome/free-solid-svg-icons';
import { faGithub, faLinkedin, faStackOverflow } from '@fortawesome/free-brands-svg-icons';

export const faIconsList = [
  faUser,
  faIdCard,
  faContactCard,
  faBlog,
  faContactBook,
  faArrowRightToBracket,
  faCircleInfo,
  faXmark,
  faTriangleExclamation,
  faCircleExclamation,
  faCheck,
  faEnvelope,
  faPhone,
  faMapLocationDot,
  faGithub,
  faLinkedin,
  faStackOverflow,
  faPassport,
  faCalendarDays,
  faXmark,
  faPenToSquare,
  faGraduationCap,
  faSchoolCircleCheck,
  faCode,
  faListCheck,
  faLanguage,
  faUsersLine,
  faCertificate,
  faChevronRight,
  faChevronLeft,
] as const;

export type FaIconType = (typeof faIconsList)[number];
